
import os
import time

os.system("qsub decode_1_unconscious_q")
time.sleep(1)
os.system("qsub decode_1_glimpse_q")
time.sleep(1)
os.system("qsub decode_1_conscious_q")
time.sleep(1)
os.system("qsub decode_2_unconscious_q")
time.sleep(1)
os.system("qsub decode_2_glimpse_q")
time.sleep(1)
os.system("qsub decode_2_conscious_q")
time.sleep(1)
os.system("qsub decode_3_unconscious_q")
time.sleep(1)
os.system("qsub decode_3_glimpse_q")
time.sleep(1)
os.system("qsub decode_3_conscious_q")
time.sleep(1)
os.system("qsub decode_4_unconscious_q")
time.sleep(1)
os.system("qsub decode_4_glimpse_q")
time.sleep(1)
os.system("qsub decode_4_conscious_q")
time.sleep(1)
os.system("qsub decode_5_unconscious_q")
time.sleep(1)
os.system("qsub decode_5_glimpse_q")
time.sleep(1)
os.system("qsub decode_5_conscious_q")
time.sleep(1)
os.system("qsub decode_6_unconscious_q")
time.sleep(1)
os.system("qsub decode_6_glimpse_q")
time.sleep(1)
os.system("qsub decode_6_conscious_q")
time.sleep(1)
os.system("qsub decode_7_unconscious_q")
time.sleep(1)
os.system("qsub decode_7_glimpse_q")
time.sleep(1)
os.system("qsub decode_7_conscious_q")
time.sleep(1)
os.system("qsub decode_8_unconscious_q")
time.sleep(1)
os.system("qsub decode_8_glimpse_q")
time.sleep(1)
os.system("qsub decode_8_conscious_q")
time.sleep(1)
os.system("qsub decode_9_unconscious_q")
time.sleep(1)
os.system("qsub decode_9_glimpse_q")
time.sleep(1)
os.system("qsub decode_9_conscious_q")
time.sleep(1)
os.system("qsub decode_10_unconscious_q")
time.sleep(1)
os.system("qsub decode_10_glimpse_q")
time.sleep(1)
os.system("qsub decode_10_conscious_q")
time.sleep(1)
os.system("qsub decode_11_unconscious_q")
time.sleep(1)
os.system("qsub decode_11_glimpse_q")
time.sleep(1)
os.system("qsub decode_11_conscious_q")
time.sleep(1)
os.system("qsub decode_12_unconscious_q")
time.sleep(1)
os.system("qsub decode_12_glimpse_q")
time.sleep(1)
os.system("qsub decode_12_conscious_q")
time.sleep(1)
os.system("qsub decode_13_unconscious_q")
time.sleep(1)
os.system("qsub decode_13_glimpse_q")
time.sleep(1)
os.system("qsub decode_13_conscious_q")
time.sleep(1)
os.system("qsub decode_14_unconscious_q")
time.sleep(1)
os.system("qsub decode_14_glimpse_q")
time.sleep(1)
os.system("qsub decode_14_conscious_q")
time.sleep(1)
os.system("qsub decode_15_unconscious_q")
time.sleep(1)
os.system("qsub decode_15_glimpse_q")
time.sleep(1)
os.system("qsub decode_15_conscious_q")
time.sleep(1)
os.system("qsub decode_16_unconscious_q")
time.sleep(1)
os.system("qsub decode_16_glimpse_q")
time.sleep(1)
os.system("qsub decode_16_conscious_q")
time.sleep(1)
os.system("qsub decode_17_unconscious_q")
time.sleep(1)
os.system("qsub decode_17_glimpse_q")
time.sleep(1)
os.system("qsub decode_17_conscious_q")
time.sleep(1)
os.system("qsub decode_18_unconscious_q")
time.sleep(1)
os.system("qsub decode_18_glimpse_q")
time.sleep(1)
os.system("qsub decode_18_conscious_q")
time.sleep(1)
os.system("qsub decode_19_unconscious_q")
time.sleep(1)
os.system("qsub decode_19_glimpse_q")
time.sleep(1)
os.system("qsub decode_19_conscious_q")
time.sleep(1)
os.system("qsub decode_20_unconscious_q")
time.sleep(1)
os.system("qsub decode_20_glimpse_q")
time.sleep(1)
os.system("qsub decode_20_conscious_q")
time.sleep(1)
os.system("qsub decode_21_unconscious_q")
time.sleep(1)
os.system("qsub decode_21_glimpse_q")
time.sleep(1)
os.system("qsub decode_21_conscious_q")
time.sleep(1)
os.system("qsub decode_22_unconscious_q")
time.sleep(1)
os.system("qsub decode_22_glimpse_q")
time.sleep(1)
os.system("qsub decode_22_conscious_q")
time.sleep(1)
os.system("qsub decode_23_unconscious_q")
time.sleep(1)
os.system("qsub decode_23_glimpse_q")
time.sleep(1)
os.system("qsub decode_23_conscious_q")
time.sleep(1)
os.system("qsub decode_24_unconscious_q")
time.sleep(1)
os.system("qsub decode_24_glimpse_q")
time.sleep(1)
os.system("qsub decode_24_conscious_q")
