
import os
import time

os.system("qsub encode_1_q")
time.sleep(3)
os.system("qsub encode_2_q")
time.sleep(3)
os.system("qsub encode_3_q")
time.sleep(3)
os.system("qsub encode_4_q")
time.sleep(3)
os.system("qsub encode_5_q")
time.sleep(3)
os.system("qsub encode_6_q")
time.sleep(3)
os.system("qsub encode_7_q")
time.sleep(3)
os.system("qsub encode_8_q")
time.sleep(3)
os.system("qsub encode_9_q")
time.sleep(3)
os.system("qsub encode_10_q")
time.sleep(3)
os.system("qsub encode_11_q")
time.sleep(3)
os.system("qsub encode_12_q")
time.sleep(3)
os.system("qsub encode_13_q")
time.sleep(3)
os.system("qsub encode_14_q")
time.sleep(3)
os.system("qsub encode_15_q")
time.sleep(3)
os.system("qsub encode_16_q")
time.sleep(3)
os.system("qsub encode_17_q")
time.sleep(3)
os.system("qsub encode_18_q")
time.sleep(3)
os.system("qsub encode_19_q")
time.sleep(3)
os.system("qsub encode_20_q")
time.sleep(3)
os.system("qsub encode_21_q")
time.sleep(3)
os.system("qsub encode_22_q")
time.sleep(3)
os.system("qsub encode_23_q")
time.sleep(3)
os.system("qsub encode_24_q")
