import os
os.system('python "preprocessing EEG with adjust onsets (aingere_5_16_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (alba_6_10_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (alvaro_5_16_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (ana_5_21_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (clara_5_22_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (inaki_5_9_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (jesica_6_7_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (leyre_5_13_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (lierni_5_20_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (maria_6_5_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (matie_5_23_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (mattin_7_12_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (out_7_19_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (pedro_5_14_2019).py"')
os.system('python "preprocessing EEG with adjust onsets (xabier_5_15_2019).py"')
