
import os
import time

os.system("qsub decode_lh-fusiform_q")
time.sleep(3)
os.system("qsub decode_lh-inferiorparietal_q")
time.sleep(3)
os.system("qsub decode_lh-inferiortemporal_q")
time.sleep(3)
os.system("qsub decode_lh-lateraloccipital_q")
time.sleep(3)
os.system("qsub decode_lh-lingual_q")
time.sleep(3)
os.system("qsub decode_lh-parahippocampal_q")
time.sleep(3)
os.system("qsub decode_lh-pericalcarine_q")
time.sleep(3)
os.system("qsub decode_lh-precuneus_q")
time.sleep(3)
os.system("qsub decode_lh-rostralmiddlefrontal_q")
time.sleep(3)
os.system("qsub decode_lh-superiorfrontal_q")
time.sleep(3)
os.system("qsub decode_lh-superiorparietal_q")
time.sleep(3)
os.system("qsub decode_lh-ventrolateralPFC_q")
time.sleep(3)
os.system("qsub decode_rh-fusiform_q")
time.sleep(3)
os.system("qsub decode_rh-inferiorparietal_q")
time.sleep(3)
os.system("qsub decode_rh-inferiortemporal_q")
time.sleep(3)
os.system("qsub decode_rh-lateraloccipital_q")
time.sleep(3)
os.system("qsub decode_rh-lingual_q")
time.sleep(3)
os.system("qsub decode_rh-parahippocampal_q")
time.sleep(3)
os.system("qsub decode_rh-pericalcarine_q")
time.sleep(3)
os.system("qsub decode_rh-precuneus_q")
time.sleep(3)
os.system("qsub decode_rh-rostralmiddlefrontal_q")
time.sleep(3)
os.system("qsub decode_rh-superiorfrontal_q")
time.sleep(3)
os.system("qsub decode_rh-superiorparietal_q")
time.sleep(3)
os.system("qsub decode_rh-ventrolateralPFC_q")
