
import os
import time

os.system("qsub decode_lh_fusif_q")
time.sleep(30)
os.system("qsub decode_lh_infpar_q")
time.sleep(30)
os.system("qsub decode_lh_inftemp_q")
time.sleep(30)
os.system("qsub decode_lh_latoccip_q")
time.sleep(30)
os.system("qsub decode_lh_lingual_q")
time.sleep(30)
os.system("qsub decode_lh_middlefrontal_q")
time.sleep(30)
os.system("qsub decode_lh_pericalc_q")
time.sleep(30)
os.system("qsub decode_lh_phipp_q")
time.sleep(30)
os.system("qsub decode_lh_precun_q")
time.sleep(30)
os.system("qsub decode_lh_sfrontal_q")
time.sleep(30)
os.system("qsub decode_lh_superiorparietal_q")
time.sleep(30)
os.system("qsub decode_lh_ventrollateralPFC_q")
time.sleep(30)
os.system("qsub decode_rh_fusif_q")
time.sleep(30)
os.system("qsub decode_rh_infpar_q")
time.sleep(30)
os.system("qsub decode_rh_inftemp_q")
time.sleep(30)
os.system("qsub decode_rh_latoccip_q")
time.sleep(30)
os.system("qsub decode_rh_lingual_q")
time.sleep(30)
os.system("qsub decode_rh_middlefrontal_q")
time.sleep(30)
os.system("qsub decode_rh_pericalc_q")
time.sleep(30)
os.system("qsub decode_rh_phipp_q")
time.sleep(30)
os.system("qsub decode_rh_precun_q")
time.sleep(30)
os.system("qsub decode_rh_sfrontal_q")
time.sleep(30)
os.system("qsub decode_rh_superiorparietal_q")
time.sleep(30)
os.system("qsub decode_rh_ventrollateralPFC_q")
