#!/bin/bash
#PBS -q bcbl
#PBS -l nodes=1:ppn=16
#PBS -l mem=16gb
#PBS -l cput=900:00:00
#PBS -N features
#PBS -o out_feature.txt
#PBS -e err_feature.txt
cd $PBS_O_WORKDIR
export PATH="/scratch/ningmei/anaconda3/bin:/scratch/ningmei/anaconda3/condabin:$PATH"
source activate keras-2.1.6_tensorflow-2.0.0
pwd
python "get computer vision features tensorflow.py"

