#!/bin/bash
#PBS -q bcbl
#PBS -l nodes=1:ppn=16
#PBS -l mem=32gb
#PBS -l cput=200:00:00
#PBS -N SN4
#PBS -o spaceNet_outputs/out_spaceNet4
#PBS -e spaceNet_outputs/err_spaceNet4
cd $PBS_O_WORKDIR
export PATH="/scratch/ningmei/anaconda3/bin:$PATH"
pwd
python "spaceNet.py"
