
import os
import time

os.system("qsub RSA_1_q")
time.sleep(3)
os.system("qsub RSA_2_q")
time.sleep(3)
os.system("qsub RSA_3_q")
time.sleep(3)
os.system("qsub RSA_4_q")
time.sleep(3)
os.system("qsub RSA_5_q")
time.sleep(3)
os.system("qsub RSA_6_q")
time.sleep(3)
os.system("qsub RSA_7_q")
time.sleep(3)
os.system("qsub RSA_8_q")
time.sleep(3)
os.system("qsub RSA_9_q")
time.sleep(3)
os.system("qsub RSA_10_q")
time.sleep(3)
os.system("qsub RSA_11_q")
time.sleep(3)
os.system("qsub RSA_12_q")
time.sleep(3)
os.system("qsub RSA_13_q")
time.sleep(3)
os.system("qsub RSA_14_q")
time.sleep(3)
os.system("qsub RSA_15_q")
time.sleep(3)
os.system("qsub RSA_16_q")
time.sleep(3)
os.system("qsub RSA_17_q")
time.sleep(3)
os.system("qsub RSA_18_q")
time.sleep(3)
os.system("qsub RSA_19_q")
time.sleep(3)
os.system("qsub RSA_20_q")
time.sleep(3)
os.system("qsub RSA_21_q")
time.sleep(3)
os.system("qsub RSA_22_q")
time.sleep(3)
os.system("qsub RSA_23_q")
time.sleep(3)
os.system("qsub RSA_24_q")
