
import os
import time

os.system("qsub RSA_unconscious_1_q")

os.system("qsub RSA_glimpse_1_q")

os.system("qsub RSA_conscious_1_q")
time.sleep(1)
os.system("qsub RSA_unconscious_2_q")
time.sleep(1)
os.system("qsub RSA_glimpse_2_q")
time.sleep(1)
os.system("qsub RSA_conscious_2_q")
time.sleep(1)
os.system("qsub RSA_unconscious_3_q")
time.sleep(1)
os.system("qsub RSA_glimpse_3_q")
time.sleep(1)
os.system("qsub RSA_conscious_3_q")
time.sleep(1)
os.system("qsub RSA_unconscious_4_q")
time.sleep(1)
os.system("qsub RSA_glimpse_4_q")
time.sleep(1)
os.system("qsub RSA_conscious_4_q")
time.sleep(1)
os.system("qsub RSA_unconscious_5_q")
time.sleep(1)
os.system("qsub RSA_glimpse_5_q")
time.sleep(1)
os.system("qsub RSA_conscious_5_q")
time.sleep(1)
os.system("qsub RSA_unconscious_6_q")
time.sleep(1)
os.system("qsub RSA_glimpse_6_q")
time.sleep(1)
os.system("qsub RSA_conscious_6_q")
time.sleep(1)
os.system("qsub RSA_unconscious_7_q")
time.sleep(1)
os.system("qsub RSA_glimpse_7_q")
time.sleep(1)
os.system("qsub RSA_conscious_7_q")
time.sleep(1)
os.system("qsub RSA_unconscious_8_q")
time.sleep(1)
os.system("qsub RSA_glimpse_8_q")
time.sleep(1)
os.system("qsub RSA_conscious_8_q")
time.sleep(1)
os.system("qsub RSA_unconscious_9_q")
time.sleep(1)
os.system("qsub RSA_glimpse_9_q")
time.sleep(1)
os.system("qsub RSA_conscious_9_q")
time.sleep(1)
os.system("qsub RSA_unconscious_10_q")
time.sleep(1)
os.system("qsub RSA_glimpse_10_q")
time.sleep(1)
os.system("qsub RSA_conscious_10_q")
time.sleep(1)
os.system("qsub RSA_unconscious_11_q")
time.sleep(1)
os.system("qsub RSA_glimpse_11_q")
time.sleep(1)
os.system("qsub RSA_conscious_11_q")
time.sleep(1)
os.system("qsub RSA_unconscious_12_q")
time.sleep(1)
os.system("qsub RSA_glimpse_12_q")
time.sleep(1)
os.system("qsub RSA_conscious_12_q")
time.sleep(1)
os.system("qsub RSA_unconscious_13_q")
time.sleep(1)
os.system("qsub RSA_glimpse_13_q")
time.sleep(1)
os.system("qsub RSA_conscious_13_q")
time.sleep(1)
os.system("qsub RSA_unconscious_14_q")
time.sleep(1)
os.system("qsub RSA_glimpse_14_q")
time.sleep(1)
os.system("qsub RSA_conscious_14_q")
time.sleep(1)
os.system("qsub RSA_unconscious_15_q")
time.sleep(1)
os.system("qsub RSA_glimpse_15_q")
time.sleep(1)
os.system("qsub RSA_conscious_15_q")
time.sleep(1)
os.system("qsub RSA_unconscious_16_q")
time.sleep(1)
os.system("qsub RSA_glimpse_16_q")
time.sleep(1)
os.system("qsub RSA_conscious_16_q")
time.sleep(1)
os.system("qsub RSA_unconscious_17_q")
time.sleep(1)
os.system("qsub RSA_glimpse_17_q")
time.sleep(1)
os.system("qsub RSA_conscious_17_q")
time.sleep(1)
os.system("qsub RSA_unconscious_18_q")
time.sleep(1)
os.system("qsub RSA_glimpse_18_q")
time.sleep(1)
os.system("qsub RSA_conscious_18_q")
time.sleep(1)
os.system("qsub RSA_unconscious_19_q")
time.sleep(1)
os.system("qsub RSA_glimpse_19_q")
time.sleep(1)
os.system("qsub RSA_conscious_19_q")
time.sleep(1)
os.system("qsub RSA_unconscious_20_q")
time.sleep(1)
os.system("qsub RSA_glimpse_20_q")
time.sleep(1)
os.system("qsub RSA_conscious_20_q")
time.sleep(1)
os.system("qsub RSA_unconscious_21_q")
time.sleep(1)
os.system("qsub RSA_glimpse_21_q")
time.sleep(1)
os.system("qsub RSA_conscious_21_q")
time.sleep(1)
os.system("qsub RSA_unconscious_22_q")
time.sleep(1)
os.system("qsub RSA_glimpse_22_q")
time.sleep(1)
os.system("qsub RSA_conscious_22_q")
time.sleep(1)
os.system("qsub RSA_unconscious_23_q")
time.sleep(1)
os.system("qsub RSA_glimpse_23_q")
time.sleep(1)
os.system("qsub RSA_conscious_23_q")
time.sleep(1)
os.system("qsub RSA_unconscious_24_q")
time.sleep(1)
os.system("qsub RSA_glimpse_24_q")
time.sleep(1)
os.system("qsub RSA_conscious_24_q")
