
import os
import time

os.system("qsub decode_1_q")
time.sleep(1)
os.system("qsub decode_2_q")
time.sleep(1)
os.system("qsub decode_3_q")
time.sleep(1)
os.system("qsub decode_4_q")
time.sleep(1)
os.system("qsub decode_5_q")
time.sleep(1)
os.system("qsub decode_6_q")
time.sleep(1)
os.system("qsub decode_7_q")
time.sleep(1)
os.system("qsub decode_8_q")
time.sleep(1)
os.system("qsub decode_9_q")
time.sleep(1)
os.system("qsub decode_10_q")
time.sleep(1)
os.system("qsub decode_11_q")
time.sleep(1)
os.system("qsub decode_12_q")
time.sleep(1)
os.system("qsub decode_13_q")
time.sleep(1)
os.system("qsub decode_14_q")
time.sleep(1)
os.system("qsub decode_15_q")
time.sleep(1)
os.system("qsub decode_16_q")
time.sleep(1)
os.system("qsub decode_17_q")
time.sleep(1)
os.system("qsub decode_18_q")
time.sleep(1)
os.system("qsub decode_19_q")
time.sleep(1)
os.system("qsub decode_20_q")
time.sleep(1)
os.system("qsub decode_21_q")
time.sleep(1)
os.system("qsub decode_22_q")
time.sleep(1)
os.system("qsub decode_23_q")
time.sleep(1)
os.system("qsub decode_24_q")
