
import os
import time

os.system("qsub RSA_1_unconscious_q")
time.sleep(3)
os.system("qsub RSA_1_glimpse_q")
time.sleep(3)
os.system("qsub RSA_1_conscious_q")
time.sleep(3)
os.system("qsub RSA_2_unconscious_q")
time.sleep(3)
os.system("qsub RSA_2_glimpse_q")
time.sleep(3)
os.system("qsub RSA_2_conscious_q")
time.sleep(3)
os.system("qsub RSA_3_unconscious_q")
time.sleep(3)
os.system("qsub RSA_3_glimpse_q")
time.sleep(3)
os.system("qsub RSA_3_conscious_q")
time.sleep(3)
os.system("qsub RSA_4_unconscious_q")
time.sleep(3)
os.system("qsub RSA_4_glimpse_q")
time.sleep(3)
os.system("qsub RSA_4_conscious_q")
time.sleep(3)
os.system("qsub RSA_5_unconscious_q")
time.sleep(3)
os.system("qsub RSA_5_glimpse_q")
time.sleep(3)
os.system("qsub RSA_5_conscious_q")
time.sleep(3)
os.system("qsub RSA_6_unconscious_q")
time.sleep(3)
os.system("qsub RSA_6_glimpse_q")
time.sleep(3)
os.system("qsub RSA_6_conscious_q")
time.sleep(3)
os.system("qsub RSA_7_unconscious_q")
time.sleep(3)
os.system("qsub RSA_7_glimpse_q")
time.sleep(3)
os.system("qsub RSA_7_conscious_q")
